using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/*
 ѓhѓ‰ѓЂ
 •\— ‚Й‚Р‚Б‚­‚и•Ф‚й
 */

public class Drum_FlipOn : MonoBehaviour
{
    float timer = 999f;
    float startZ;
    float endZ;

    [Header("Bounce Rotation ђЭ’и")]
    public float damping = 1f;      // ЊёђЉ
    public float frequency = 18f;   // —h‚к‘¬“x
    public float maxTime = 0.4f;    // —h‚к‘±‚­ЋћЉФ

    bool isFront = true;


    void OnEnable()
    {
        AdxMarkerBroadcaster.OnMarkerReceived += OnMarker;
    }

    void OnDisable()
    {
        AdxMarkerBroadcaster.OnMarkerReceived -= OnMarker;
    }

    void OnMarker(string tag)
    {
        if (tag == "JUMP")
        {
            timer = 0f;

            isFront = !isFront;

            startZ = transform.eulerAngles.z;

            endZ = isFront ? 0f : 180f;
        }
    }

    void Update()
    {
        timer += Time.deltaTime;
        if (timer > maxTime)
        {
            transform.rotation = Quaternion.Euler(0, 0, endZ);
            return;
        }

        float t = timer;

        float wave = 1f - Mathf.Exp(-damping * t) * Mathf.Cos(frequency * t);

        float z = Mathf.Lerp(startZ, endZ, wave);

        transform.rotation = Quaternion.Euler(0, 0, z);
    }
}

