using UnityEngine;

public class BeatChecker : MonoBehaviour
{
    private Renderer rend;
    private Color originalColor;
    private Color beatColor = Color.red;

    private float flashTimer = 0f;
    private float flashDuration = 0.1f;

    private bool isMarker = false;

    long markerDspTime;
    long jumpDspTime;


    private void OnEnable()
    {
        AdxMarkerBroadcaster.OnMarkerReceived += OnSequencerCallback;
    }

    private void OnDisable()
    {
        AdxMarkerBroadcaster.OnMarkerReceived -= OnSequencerCallback;
    }

    void Start()
    {
        rend = GetComponent<Renderer>();
        originalColor = rend.material.color;
    }

    // ---- ƒRپ[ƒ‹ƒoƒbƒNپF‚±‚±‚إ‚حگâ‘خ‚ةگF‚ً•د‚¦‚ب‚¢ ----
    void OnSequencerCallback(string tag)
    {
        if (tag == "JUMP")
        {
            markerDspTime = DededeJump2.Instance.music.time;
            isMarker = true;
        }
    }

    // ---- ‘S‚ؤ‚ج•`‰و‚ح Update ‚ةŒإ’è ----
    void Update()
    {
        // Œُ‚ç‚¹‚é—v‹پ‚ھ—ˆ‚½
        if (isMarker)
        {
            isMarker = false;

            rend.material.color = beatColor;
            flashTimer = flashDuration;

            jumpDspTime = DededeJump2.Instance.music.time;
            long delay = jumpDspTime - markerDspTime;
            //UnityEngine.Debug.Log($"ƒ}پ[ƒJپ[پF{markerDspTime},‚ذ‚©‚é : {jumpDspTime},’x‰„: {delay} ");
        }

        // ƒtƒ‰ƒbƒVƒ…ڈI—¹ڈˆ—‌
        if (flashTimer > 0f)
        {
            flashTimer -= Time.deltaTime;
            if (flashTimer <= 0f)
            {
                rend.material.color = originalColor;
            }
        }
    }
}
